---
abstract: 'Override subroutines in a module for unit testing'
author:
  - 'Simon Flack'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.133380'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-MockModule
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  SUPER: 0
  Scalar::Util: 0
  Test::More: 0.45
version: 0.06_1
